# -*- coding: utf-8 -*-
"""Week1_Bitcoin_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eURGilDeEinTPqfXKRehh2UHt3wM15jj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

!pip install yfinance
import yfinance as yf

# Download last 2 years of Bitcoin data
btc = yf.download("BTC-USD", start="2023-01-01", end="2025-01-01")

btc.head()

# Basic info
print(btc.info())

# Summary stats
print(btc.describe())

# First few rows
btc.head()

# % Change in closing price
btc['Daily_Return'] = btc['Close'].pct_change()

# Show first 10 returns
btc['Daily_Return'].head(10)

plt.figure(figsize=(12,6))
plt.plot(btc['Close'], label="BTC Closing Price")
plt.title("Bitcoin Price (2023-2024)")
plt.xlabel("Date")
plt.ylabel("Price in USD")
plt.legend()
plt.show()

plt.figure(figsize=(12,6))
btc['Daily_Return'].plot(kind='hist', bins=50, alpha=0.7)
plt.title("Distribution of Bitcoin Daily Returns")
plt.xlabel("Daily Return")
plt.show()

btc['SMA_30'] = btc['Close'].rolling(window=30).mean()

plt.figure(figsize=(12,6))
plt.plot(btc['Close'], label="BTC Price", alpha=0.7)
plt.plot(btc['SMA_30'], label="30-Day SMA", color='orange')
plt.title("BTC Price vs 30-Day SMA")
plt.legend()
plt.show()